# Generated by Django 3.2.7 on 2021-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0002_setting_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('uuid', models.UUIDField(unique=True, verbose_name='UUID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('pubkey', models.TextField(verbose_name='public key')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
