# Generated by Django 3.2.7 on 2021-10-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0003_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('hosts', models.ManyToManyField(blank=True, to='remotes.Host', verbose_name='Hosts')),
            ],
            options={
                'verbose_name': 'Hosts group',
                'verbose_name_plural': 'Hosts groups',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
