# Generated by Django 3.2.7 on 2021-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0004_hostsgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Variable type',
                'verbose_name_plural': 'Variable types',
                'ordering': ['name'],
            },
        ),
    ]
