# Generated by Django 3.2.7 on 2021-10-09 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0007_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('variable', models.CharField(blank=True, max_length=255, verbose_name='variable')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('after', models.DateTimeField(blank=True, null=True, verbose_name='after')),
                ('before', models.DateTimeField(blank=True, null=True, verbose_name='before')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remotes.command', verbose_name='command')),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remotes.hostsgroup', verbose_name='hosts')),
            ],
            options={
                'verbose_name': 'Command queue',
                'verbose_name_plural': 'Command queues',
                'ordering': ['hosts', 'order', '-is_active', 'command'],
            },
        ),
    ]
