# Generated by Django 3.2.7 on 2021-10-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0009_host_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='pubkey',
            field=models.TextField(blank=True, null=True, verbose_name='public key'),
        ),
    ]
