# Generated by Django 3.2.7 on 2021-10-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0010_host_pubkey_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandqueue',
            options={'ordering': ['hosts', 'name', 'order', '-is_active', 'command'], 'verbose_name': 'Command queue', 'verbose_name_plural': 'Command queues'},
        ),
        migrations.AlterField(
            model_name='commandqueue',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='commandqueue',
            unique_together={('hosts', 'name', 'order')},
        ),
    ]
