# Generated by Django 3.2.7 on 2021-10-18 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0011_command_queue_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('order', models.PositiveIntegerField(default=1, unique=True, verbose_name='order')),
                ('after', models.DateTimeField(blank=True, null=True, verbose_name='after')),
                ('before', models.DateTimeField(blank=True, null=True, verbose_name='before')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remotes.hostsgroup', verbose_name='hosts')),
            ],
            options={
                'verbose_name': 'Commands group',
                'verbose_name_plural': 'Commands groups',
                'ordering': ['order', 'hosts', 'name', '-is_active'],
            },
        ),
    ]
