# Generated by Django 3.2.7 on 2021-10-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0012_commands_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandQueue',
        ),
    ]
