# Generated by Django 3.2.7 on 2021-10-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0013_command_queue_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandsGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('variable', models.CharField(blank=True, max_length=255, verbose_name='variable')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remotes.command', verbose_name='command')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remotes.commandsgroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'Commands group item',
                'verbose_name_plural': 'Commands group items',
                'ordering': ['group', 'order', 'name', '-is_active', 'command'],
                'unique_together': {('group', 'name')},
            },
        ),
    ]
