# Generated by Django 3.2.7 on 2021-10-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0014_commands_group_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandsOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField(blank=True, null=True, verbose_name='output')),
                ('result', models.TextField(blank=True, null=True, verbose_name='result')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='timestamp')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remotes.command', verbose_name='command')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remotes.host', verbose_name='host')),
            ],
            options={
                'verbose_name': 'Commands output',
                'verbose_name_plural': 'Commands outputs',
                'ordering': ['timestamp', 'host', 'command'],
            },
        ),
    ]
