# Generated by Django 3.2.7 on 2021-10-20 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0016_commands_group_before_after'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandsoutput',
            options={'ordering': ['timestamp', 'group_item_id'], 'verbose_name': 'Commands output', 'verbose_name_plural': 'Commands outputs'},
        ),
        migrations.RemoveField(
            model_name='commandsoutput',
            name='command',
        ),
        migrations.RemoveField(
            model_name='commandsoutput',
            name='host',
        ),
        migrations.AddField(
            model_name='commandsoutput',
            name='group_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remotes.commandsgroupitem', verbose_name='group item'),
        ),
    ]
