# Generated by Django 3.2.7 on 2021-10-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0017_command_output_group_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandsoutput',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='timestamp'),
        ),
    ]
