# Generated by Django 3.2.7 on 2021-10-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0018_commands_output_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='type',
        ),
        migrations.DeleteModel(
            name='VariableType',
        ),
    ]
