# Generated by Django 3.2.7 on 2021-10-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0019_variable_type_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='description',
        ),
    ]
