# Generated by Django 3.2.7 on 2021-10-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0021_alter_host_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['-is_active', 'user', 'uuid'], 'verbose_name': 'Host', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.RemoveField(
            model_name='host',
            name='name',
        ),
    ]
