# Generated by Django 3.2.7 on 2021-10-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0022_host_name_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='timeout',
            field=models.PositiveIntegerField(default=15, verbose_name='timeout'),
        ),
    ]
