# Generated by Django 3.2.7 on 2021-10-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0024_variable_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandsoutput',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remotes.host', verbose_name='host'),
            preserve_default=False,
        ),
    ]
