# Generated by Django 3.2.7 on 2021-11-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0028_setting_hosts_group_auto_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandsgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
