# Generated by Django 3.2.9 on 2021-11-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0029_alter_commands_group_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandsoutput',
            name='group_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotes.commandsgroupitem', verbose_name='group item'),
        ),
    ]
