# Generated by Django 3.2.9 on 2021-11-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0030_commands_output_group_item_delete_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='settings',
            field=models.ManyToManyField(blank=True, to='remotes.Setting', verbose_name='settings'),
        ),
    ]
