# Generated by Django 3.2.9 on 2021-11-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0031_command_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variable',
            new_name='VariableValue',
        ),
        migrations.AlterModelOptions(
            name='variablevalue',
            options={'ordering': ['host', 'name'], 'verbose_name': 'Variable value', 'verbose_name_plural': 'Variable values'},
        ),
    ]
