# Generated by Django 3.2.9 on 2021-11-07 23:45

from django.db import migrations, models


def insert_variables(apps, schema_editor):
    """
    Copy variable names to variable objects
    """
    # Don't import the Configuration model directly as it may be a newer
    # version than this migration expects.
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    Variable = apps.get_model('remotes', 'Variable')
    for variable in CommandsGroupItem.objects.order_by('variable').values_list('variable', flat=True).distinct().exclude(variable=''):
        Variable.objects.create(name=variable)

class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0032_variable_rename_to_variable_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(code=insert_variables,
                             reverse_code=migrations.RunPython.noop)
    ]
