# Generated by Django 3.2.9 on 2021-11-07 23:55

from django.db import migrations, models
import django.db.models.deletion


def insert_variables(apps, schema_editor):
    """
    Copy variable names to variable objects
    """
    # Don't import the Configuration model directly as it may be a newer
    # version than this migration expects.
    Variable = apps.get_model('remotes', 'Variable')
    variables = {variable.name: variable for variable in Variable.objects.all()}
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.exclude(variable_name=''):
        item.variable = variables[item.variable_name]
        item.save()

def delete_variables(apps, schema_editor):
    """
    Copy variable objects to variable names
    """
    # Don't import the Configuration model directly as it may be a newer
    # version than this migration expects.
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.exclude(variable__isnull=True):
        item.variable_name = item.variable.name
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0033_variable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandsgroupitem',
            old_name='variable',
            new_name='variable_name',
        ),
        migrations.AlterField(
            model_name='commandsgroupitem',
            name='variable_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='variable name'),
        ),
        migrations.AddField(
            model_name='commandsgroupitem',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='remotes.variable', verbose_name='variable'),
        ),
        migrations.RunPython(code=insert_variables,
                             reverse_code=delete_variables),
        migrations.RemoveField(
            model_name='commandsgroupitem',
            name='variable_name',
        ),
    ]
