# Generated by Django 3.2.9 on 2021-11-08 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0034_alter_commandsgroupitem_variable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variablevalue',
            options={'ordering': ['host', 'variable'], 'verbose_name': 'Variable value', 'verbose_name_plural': 'Variable values'},
        ),
        migrations.AddField(
            model_name='variablevalue',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotes.variable', verbose_name='variable'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='variablevalue',
            unique_together={('host', 'variable')},
        ),
        migrations.RemoveField(
            model_name='variablevalue',
            name='name',
        ),
    ]
