# Generated by Django 3.2.9 on 2021-11-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0036_variable_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='variables',
            field=models.ManyToManyField(blank=True, to='remotes.Variable', verbose_name='variables'),
        ),
    ]
