# Generated by Django 3.2.9 on 2021-11-11 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0041_command_group_item_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandsgroupitemvariable',
            name='command_group_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotes.commandsgroupitem', verbose_name='command group item'),
        ),
        migrations.AlterField(
            model_name='commandsgroupitemvariable',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotes.variable', verbose_name='variable'),
        ),
    ]
