# Generated by Django 3.2.9 on 2021-11-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0042_command_group_item_variables_cascade_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['name'], 'verbose_name': 'Command', 'verbose_name_plural': 'Commands'},
        ),
        migrations.RemoveField(
            model_name='command',
            name='is_active',
        ),
    ]
