# Generated by Django 3.2.9 on 2021-11-14 19:54

from django.db import migrations, models


def insert_values(apps, schema_editor):
    """
    Copy timeout field from Command to CommandGroupItem
    """
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.all():
        item.timeout = item.command.timeout
        item.save()

def delete_values(apps, schema_editor):
    """
    Copy timeout field from CommandGroupItem to Command
    """
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.all():
        item.command.timeout = item.timeout
        item.command.save()


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0044_commands_group_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandsgroupitem',
            name='timeout',
            field=models.PositiveIntegerField(default=15, verbose_name='timeout'),
        ),
        migrations.RunPython(code=insert_values,
                             reverse_code=delete_values),
        migrations.RemoveField(
            model_name='command',
            name='timeout',
        ),
    ]
