# Generated by Django 3.2.9 on 2021-11-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0045_commands_group_item_timeout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandsgroupitem',
            old_name='variables',
            new_name='output_variables',
        ),
        migrations.AlterField(
            model_name='commandsgroupitem',
            name='output_variables',
            field=models.ManyToManyField(blank=True, related_name='output_variables_set', through='remotes.CommandsGroupItemVariable', to='remotes.Variable', verbose_name='output variables'),
        ),
    ]
