# Generated by Django 3.2.9 on 2021-11-14 20:18

from django.db import migrations, models


def insert_values(apps, schema_editor):
    """
    Copy settings field from Command to CommandGroupItem
    """
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.all():
        for setting in item.command.settings.all():
            item.settings.add(setting)

def delete_values(apps, schema_editor):
    """
    Copy settings field from CommandGroupItem to Command
    """
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.all():
        for setting in item.settings.all():
            item.command.settings.add(setting)


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0046_rename_variables_commandsgroupitem_output_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandsgroupitem',
            name='settings',
            field=models.ManyToManyField(blank=True, to='remotes.Setting', verbose_name='settings'),
        ),
        migrations.RunPython(code=insert_values,
                             reverse_code=delete_values),
        migrations.RemoveField(
            model_name='command',
            name='settings',
        ),
    ]
