# Generated by Django 3.2.9 on 2021-11-14 20:32

from django.db import migrations, models


def insert_values(apps, schema_editor):
    """
    Copy variables field from Command to CommandGroupItem
    """
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.all():
        for variable in item.command.variables.all():
            item.variables.add(variable)

def delete_values(apps, schema_editor):
    """
    Copy variables field from CommandGroupItem to Command
    """
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.all():
        for variable in item.variables.all():
            item.command.variables.add(variable)


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0047_commands_group_item_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandsgroupitem',
            name='variables',
            field=models.ManyToManyField(blank=True, to='remotes.Variable', verbose_name='variables'),
        ),
        migrations.RunPython(code=insert_values,
                             reverse_code=delete_values),
        migrations.RemoveField(
            model_name='command',
            name='variables',
        ),
    ]
