# Generated by Django 3.2.9 on 2021-11-14 22:42

from django.db import migrations, models


def insert_values(apps, schema_editor):
    """
    Copy name field from Command to CommandGroupItem
    """
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.all():
        item.name = item.command.name
        item.save()

def delete_values(apps, schema_editor):
    """
    Copy name field from CommandGroupItem to Command
    """
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.all():
        item.command.name = item.name
        item.command.save()


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0048_commands_group_item_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandsgroupitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.RunPython(code=insert_values,
                             reverse_code=delete_values),
        migrations.AlterModelOptions(
            name='command',
            options={'verbose_name': 'Command', 'verbose_name_plural': 'Commands'},
        ),
        migrations.RemoveField(
            model_name='command',
            name='name',
        ),
    ]
