# Generated by Django 3.2.9 on 2021-11-14 22:59

from django.db import migrations, models


def insert_values(apps, schema_editor):
    """
    Copy command field from Command to CommandGroupItem
    """
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.all():
        item.command_text = item.command.command
        item.save()

def delete_values(apps, schema_editor):
    """
    Copy command field from CommandGroupItem to Command
    """
    CommandsGroupItem = apps.get_model('remotes', 'CommandsGroupItem')
    for item in CommandsGroupItem.objects.all():
        item.command.command = item.command_text
        item.command.save()


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0049_commands_group_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandsgroupitem',
            options={'ordering': ['group', 'order', '-is_active', 'command_text'], 'verbose_name': 'Commands group item', 'verbose_name_plural': 'Commands group items'},
        ),
        migrations.AddField(
            model_name='commandsgroupitem',
            name='command_text',
            field=models.TextField(null=True, verbose_name='command text'),
        ),
        migrations.RunPython(code=insert_values,
                             reverse_code=delete_values),
    ]
