# Generated by Django 3.2.9 on 2021-11-14 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0052_commands_group_item_command'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommandsGroupItem',
            new_name='Command',
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['group', 'order', '-is_active'], 'verbose_name': 'Command', 'verbose_name_plural': 'Commands'},
        ),
    ]
