# Generated by Django 3.2.9 on 2021-11-14 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0053_commands_group_item_rename_command'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandsoutput',
            old_name='group_item',
            new_name='command',
        ),
        migrations.AlterModelOptions(
            name='commandsoutput',
            options={'ordering': ['timestamp', 'command_id'], 'verbose_name': 'Commands output', 'verbose_name_plural': 'Commands outputs'},
        ),
        migrations.AlterField(
            model_name='commandsgroupitemvariable',
            name='command_group_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotes.command', verbose_name='command'),
        ),
        migrations.AlterField(
            model_name='commandsoutput',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotes.command', verbose_name='command'),
        ),
    ]
