# Generated by Django 3.2.9 on 2021-11-15 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0054_commands_output_command'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandsgroupitemvariable',
            options={'ordering': ['command', 'order', 'variable'], 'verbose_name': 'Command group items variable', 'verbose_name_plural': 'Commands group items variables'},
        ),
        migrations.RenameField(
            model_name='commandsgroupitemvariable',
            old_name='command_group_item',
            new_name='command',
        ),
        migrations.AlterUniqueTogether(
            name='commandsgroupitemvariable',
            unique_together={('command', 'order')},
        ),
    ]
