# Generated by Django 3.2.9 on 2021-11-15 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0055_commands_variable_command'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommandsGroupItemVariable',
            new_name='CommandVariable',
        ),
        migrations.AlterModelOptions(
            name='commandvariable',
            options={'ordering': ['command', 'order', 'variable'], 'verbose_name': 'Command variable', 'verbose_name_plural': 'Commands variables'},
        ),
    ]
