# Generated by Django 3.2.9 on 2021-11-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0056_command_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together={('name', 'group')},
        ),
    ]
