# Generated by Django 3.2.9 on 2021-11-21 11:45

from django.contrib.auth import get_user_model
from django.db import migrations, models


def insert_values(apps, schema_editor):
    """
    Copy user to username
    """
    Request = apps.get_model('remotes', 'Request')
    for item in Request.objects.all():
        item.username = item.user.username if item.user else None
        item.save()

def delete_values(apps, schema_editor):
    """
    Copy username field to user
    """
    Request = apps.get_model('remotes', 'Request')
    User = get_user_model()
    users = {user.username: user.pk for user in User.objects.all()}
    for item in Request.objects.all():
        item.user_id = users.get(item.username, None)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0058_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='username'),
        ),
        migrations.RunPython(code=insert_values,
                             reverse_code=delete_values),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
    ]
