# Generated by Django 3.2.9 on 2021-11-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0059_request_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
