# Generated by Django 3.2.9 on 2021-11-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0060_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('message_level', models.PositiveIntegerField(verbose_name='message level')),
                ('method', models.CharField(max_length=255, verbose_name='metod')),
                ('path', models.CharField(max_length=255, verbose_name='path')),
                ('raw_uri', models.TextField(verbose_name='raw uri')),
                ('url_name', models.CharField(max_length=255, verbose_name='url name')),
                ('func_name', models.CharField(max_length=255, verbose_name='function name')),
                ('remote_addr', models.CharField(blank=True, max_length=255, verbose_name='remote address')),
                ('forwarded_for', models.CharField(blank=True, max_length=255, verbose_name='forwarded for')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('client_agent', models.CharField(blank=True, max_length=255, verbose_name='client agent')),
                ('client_version', models.CharField(blank=True, max_length=255, verbose_name='client version')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='username')),
                ('args', models.TextField(blank=True, verbose_name='arguments')),
                ('kwargs', models.TextField(blank=True, verbose_name='keyword arguments')),
                ('extra', models.TextField(blank=True, verbose_name='extra')),
            ],
            options={
                'verbose_name': 'Api log',
                'verbose_name_plural': 'Api logs',
                'db_table': 'api_log',
                'ordering': ['-date', '-time', '-id'],
            },
        ),
    ]
