# Generated by Django 3.2.9 on 2021-12-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0065_command_variables_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='settings',
            field=models.ManyToManyField(blank=True, to='remotes.Setting', verbose_name='input settings'),
        ),
    ]
