# Generated by Django 3.2.9 on 2021-12-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0066_alter_command_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='variables',
            field=models.ManyToManyField(blank=True, to='remotes.Variable', verbose_name='input variables'),
        ),
    ]
