# Generated by Django 6.0.2 on 2026-02-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remotes", "0067_alter_command_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="include_in_apilog",
            field=models.BooleanField(default=False, verbose_name="include in API log"),
        ),
    ]
