# Generated by Django 6.0.2 on 2026-03-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remotes", "0068_host_include_in_apilog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apilog",
            name="method",
            field=models.CharField(max_length=255, verbose_name="method"),
        ),
    ]
