# Generated by Django 6.0.2 on 2026-03-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remotes", "0069_apilog_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="command",
            name="execution_type",
            field=models.CharField(
                choices=[
                    ("python_file", "Python file"),
                    ("python_inline", "Python with -c"),
                    ("python_exec", "Python exec()"),
                    ("python_os_system", "Python os.system()"),
                    ("popen_args", "Command arguments"),
                    ("popen_shell", "Shell commands"),
                    ("powershell_file", "Powershell file"),
                    ("powershell_inline", "Powershell with -Command"),
                ],
                default="python_file",
                max_length=255,
                verbose_name="execution type",
            ),
        ),
    ]
